# config.yml
serverId: "local-server"
hostname: "127.0.0.1"           # Локальный IP-адрес
portForNewAccessKeys: 16459     # Порт, который будет слушаться
accessKeys: []                # Если не требуется, можно оставить пустым
metricsEnabled: false         # Отключаем метрики, если не нужно
# Добавьте другие необходимые параметры, если они требуются документацией
